---
title: "Etwas R am Abend"
author: "Norman Markgraf"
date: "06.12.2017"
institute: Standort Köln
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
    echo = TRUE,
    background='#E0E0E0',
#   fig.keep="none",
    out.width="80%",
#   cache = TRUE,
#    tidy=TRUE,wwwwwwww
    fig.align = "center",
    width.cutoff=60
)
options(width = 73)
library(mosaic)
library(tidyverse)
library(formatR)
library(mosaic)

set.seed(2009)
```

```{r child = './content/010-Einfuehrung-R.Rmd'}
```

```{r child = './content/020-Installation-R.Rmd'}
```

```{r child = './content/030-Erste-Schritte-in-R.Rmd'}
```

```{r child = './content/035-Strukturen-in-R.Rmd'}
```

```{r child = './content/037-Statistische-Funktionen.Rmd'}
```

```{r child = './content/040-Ein-paar-Schritte-in-R.Rmd'}
```

```{r child = './content/060-Eine-kurze-Datenanalyse.Rmd'}
```

```{r child = './content/070-R-intern.Rmd'}
```

```{r include=FALSE, eval=FALSE}
# Appendix
```

```{r child = './content/A010-Literatur.Rmd'}
```

```{r child = './content/A070-Videos.Rmd'}
```

```{r child = './content/A090-Copyright.Rmd'}
```

